services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto_password.txt:/mosquitto/config/password.txt:ro
      - ./logs/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
  n8n:
    image: n8nio/n8n:latest
    volumes:
      - n8n_storage:/home/node/.n8n
    ports:
      - "5678:5678"
    restart: always

volumes:
  data: ~
  n8n_storage: ~