services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto_password.txt:/mosquitto/config/password.txt:ro
      - ./logs/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
  n8n:
    image: n8nio/n8n:latest
    volumes:
      - n8n_storage:/home/node/.n8n
    ports:
      - "5678:5678"
    restart: always

volumes:
  data: ~
  cache: ~
  n8n_storage: ~